# Generated by Django 5.2.14 on 2026-05-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('precipitacion', models.FloatField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
