# Generated by Django 5.2.14 on 2026-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroclima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_promedio', models.FloatField()),
                ('humedad', models.FloatField()),
                ('precipitacion', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMeteorologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('humedad', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('fecha', models.DateField()),
                ('fuente_datos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('parroquia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitud', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroClimatico',
        ),
        migrations.AddField(
            model_name='registrometeorologico',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='agroclima.ubicacion'),
        ),
        migrations.AddField(
            model_name='condicionclimatica',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='agroclima.ubicacion'),
        ),
    ]
