# Generated by Django 5.2.14 on 2026-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('tiempo_cosecha_dias', models.PositiveIntegerField()),
                ('nivel_dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='cultivos.categoriacultivo')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('humedad_min', models.FloatField()),
                ('humedad_max', models.FloatField()),
                ('altitud_min', models.FloatField()),
                ('altitud_max', models.FloatField()),
                ('precipitacion_min', models.FloatField()),
                ('precipitacion_max', models.FloatField()),
                ('horas_sol', models.FloatField()),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='cultivos.cultivo')),
                ('tipo_suelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.tiposuelo')),
            ],
        ),
    ]
