# Generated by Django 5.2.14 on 2026-05-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitud_min', models.FloatField()),
                ('altitud_max', models.FloatField()),
                ('humedad_min', models.FloatField()),
                ('humedad_max', models.FloatField()),
                ('precipitacion_min', models.FloatField()),
                ('precipitacion_max', models.FloatField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('horas_sol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('tiempo_cosecha', models.PositiveIntegerField(help_text='Días')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.categoria')),
                ('requerimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultivos.requerimiento')),
            ],
        ),
    ]
