# Generated by Django 5.2.14 on 2026-06-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitud_min', models.FloatField()),
                ('altitud_max', models.FloatField()),
                ('horas_sol', models.FloatField()),
                ('humedad_min', models.FloatField()),
                ('humedad_max', models.FloatField()),
                ('precipitacion_min', models.FloatField()),
                ('precipitacion_max', models.FloatField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('radiacion_min', models.FloatField()),
                ('radiacion_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_planta', models.FloatField()),
                ('estado_fenologico', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='seguimientos/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('tiempo_cosecha', models.PositiveIntegerField(help_text='Días')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='cultivos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='AmenazaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.FloatField()),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.amenaza')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='CultivoTipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='CultivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField()),
                ('fecha_cosecha_real', models.DateField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
    ]
