# Generated by Django 5.2.14 on 2026-06-09 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cultivousuario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultivos.estado'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='requerimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultivos.requerimiento'),
        ),
        migrations.AddField(
            model_name='seguimientocultivo',
            name='cultivo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='cultivos.cultivousuario'),
        ),
        migrations.AddField(
            model_name='amenaza',
            name='tipo_amenaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.tipoamenaza'),
        ),
        migrations.AddField(
            model_name='cultivotiposuelo',
            name='tipo_suelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.tiposuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='amenazacultivo',
            unique_together={('cultivo', 'amenaza')},
        ),
        migrations.AlterUniqueTogether(
            name='cultivotiposuelo',
            unique_together={('cultivo', 'tipo_suelo')},
        ),
    ]
