# Generated by Django 5.2.14 on 2026-06-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='requerimiento',
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitud_min', models.FloatField()),
                ('altitud_max', models.FloatField()),
                ('horas_sol', models.FloatField()),
                ('humedad_min', models.FloatField()),
                ('humedad_max', models.FloatField()),
                ('precipitacion_min', models.FloatField()),
                ('precipitacion_max', models.FloatField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('radiacion_min', models.FloatField()),
                ('radiacion_max', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.DeleteModel(
            name='Requerimiento',
        ),
    ]
