# Generated by Django 5.2.14 on 2026-06-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_remove_cultivo_requerimiento_especificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacion',
            name='ph_max',
        ),
        migrations.RemoveField(
            model_name='especificacion',
            name='ph_min',
        ),
    ]
