# Generated by Django 5.2.14 on 2026-06-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agroclima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField()),
                ('nivel_confianza', models.FloatField()),
                ('puntaje_compatibilidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroclima.ubicacion')),
            ],
        ),
    ]
