# Generated by Django 5.2.14 on 2026-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agroclima', '0002_condicionclimatica_registrometeorologico_ubicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('peso_temperatura', models.FloatField(default=0.35)),
                ('peso_humedad', models.FloatField(default=0.2)),
                ('peso_altitud', models.FloatField(default=0.2)),
                ('peso_precipitacion', models.FloatField(default=0.15)),
                ('peso_suelo', models.FloatField(default=0.1)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_compatibilidad', models.FloatField()),
                ('nivel_confianza', models.FloatField()),
                ('recomendado', models.BooleanField(default=True)),
                ('justificacion', models.TextField()),
            ],
            options={
                'ordering': ['-puntaje_compatibilidad'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('condicion_climatica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroclima.condicionclimatica')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroclima.ubicacion')),
            ],
        ),
    ]
