# Generated by Django 5.2.14 on 2026-06-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroclima', '0001_initial'),
        ('recomendaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='tipo_consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='consulta',
            name='condicion_climatica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agroclima.condicionclimatica'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoConsulta',
        ),
    ]
