# Generated by Django 5.2.14 on 2026-05-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultarecomendacion',
            name='regla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='recomendaciones.regladecision'),
        ),
    ]
