# Generated by Django 5.2.14 on 2026-06-09 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol'),
        ),
    ]
